// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'asdP': string;
  'avatarBar': string;
  'avatarImage': string;
  'avatarText': string;
  'card': string;
  'header': string;
  'icon': string;
  'messageBar': string;
}
export const cssExports: CssExports;
export default cssExports;
