// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatarBar': string;
  'avatarImage': string;
  'avatarText': string;
}
export const cssExports: CssExports;
export default cssExports;
